version: 2
jobs:
  checkout_and_setup:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-build:php-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-packages-{{ checksum "composer.json" }}
            - composer-packages-
      - run: composer install
      - run: cp .env.example .env
      - run: php artisan key:generate
      - save_cache:
          paths:
            - ./vendor
          key: composer-packages-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  test:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-test:php-laravel
    steps:
      - attach_workspace:
          at: .
      - run: phpunit
  build_framework:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-build:php-laravel
    steps:
      - attach_workspace:
          at: .
      - run: php artisan config:cache
      - run: php artisan route:cache
      - run: php artisan view:cache
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./bootstrap/*
            - ./storage/*
  build_static:
    working_directory: ~/repo
    docker:
      - image: kkarczmarczyk/node-yarn:8.0
    steps:
      - attach_workspace:
          at: .
      - run: yarn --production
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./public/*
  package:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker build -t tristanpixls/dokr:${CIRCLE_SHA1} .
  deploy:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: .

workflows:
  version: 2
  continous-deployment:
    jobs:
      - checkout_and_setup
      - test:
          requires:
            - checkout_and_setup
      - build_framework:
          requires:
            - test
      - build_static:
          requires:
            - test
      - package:
          requires:
            - build_framework
            - build_static
      - approve_before_prod_deploy:
          type: approval
          requires:
            - package
      - deploy:
          requires:
            - approve_before_prod_deploy
