version: 2
jobs:
  checkout_and_setup:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-build:php-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-packages-{{ checksum "composer.json" }}
            - composer-packages-
      - run: composer install
      - run: cp .env.example .env
      - run: php artisan key:generate
      - save_cache:
          paths:
            - ./vendor
          key: composer-packages-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  test:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-test:php-laravel
    steps:
      - attach_workspace:
          at: .
      - run: phpunit
  build:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker build -t tristanpixls/dokr:${CIRCLE_SHA1} .
  deploy:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: .

workflows:
  version: 2
  continous-deployment:
    jobs:
      - checkout_and_setup
      - test:
          requires:
            - checkout_and_setup
      - build:
          requires:
            - test
      - approve_before_prod_deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approve_before_prod_deploy
