version: 2
jobs:
  checkout_and_setup:
    working_directory: ~/repo
    docker:
      - image: unitedclassifiedsapps/php7-node-composer:7.2-02
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - run: cp .env.example .env
      - run: php artisan key:generate
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  test:
    working_directory: ~/repo
    docker:
      - image: unitedclassifiedsapps/php7-node-composer:7.2-02
    steps:
      - attach_workspace:
          at: ~
      - run: pwd
      - run: ls -la
      - run: phpunit
  build:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: ~
      - run: docker-compose build
  deploy:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: ~

workflows:
  version: 2
  continous-deployment:
    jobs:
      - checkout_and_setup
      - test:
          requires:
            - checkout_and_setup
      - build:
          requires:
            - test
      - approve_before_prod_deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approve_before_prod_deploy
