version: 2
jobs:
  checkout_and_setup:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-build:php-laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-packages-{{ checksum "composer.json" }}
            - composer-packages-
      - run: composer install
      - run: cp .env.example .env
      - run: php artisan key:generate
      - save_cache:
          paths:
            - ./vendor
          key: composer-packages-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  test:
    working_directory: ~/repo
    docker:
      - image: tristanpixls/enzyme-test:php-laravel
    steps:
      - attach_workspace:
          at: .
      - run: phpunit
  build_static:
    working_directory: ~/repo
    docker:
      - image: kkarczmarczyk/node-yarn:8.0
    steps:
      - attach_workspace:
          at: .
      - run: yarn --production
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./public/*
  package_and_deploy:
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker build -t test/dokr .
      - run: $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - run: docker tag test/dokr:latest 602942109470.dkr.ecr.ap-southeast-2.amazonaws.com/test/dokr:${CIRCLE_SHA1}
      - run: docker push 602942109470.dkr.ecr.ap-southeast-2.amazonaws.com/test/dokr:${CIRCLE_SHA1}

workflows:
  version: 2
  continous-deployment:
    jobs:
      - checkout_and_setup
      - test:
          requires:
            - checkout_and_setup
      - build_static:
          requires:
            - test
      - package_and_deploy:
          requires:
            - build_static
